-- 用户表
DROP TABLE IF EXISTS T_USER;
CREATE TABLE T_USER(
	ID          BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	USER_NAME   VARCHAR(30)     DEFAULT NULL COMMENT '用户名',
	USER_CODE   VARCHAR(7)      NOT NULL COMMENT '用户编号/登录账号',
	PASS_WORD   VARCHAR(32)     NOT NULL COMMENT '密码(密文)',
	SALT        VARCHAR(16)     NOT NULL COMMENT '盐',
	BANK_NO     VARCHAR(3)      NOT NULL COMMENT '银行号',
	ROLES       VARCHAR(30)     DEFAULT NULL COMMENT '角色',
	PERMS       VARCHAR(200)    DEFAULT NULL COMMENT '权限(以英文逗号隔开)',
	`STATUS`    INT             DEFAULT 0 COMMENT '状态[-1失效，0-正常，1-锁定]',
	PRIMARY KEY (id),
	UNIQUE KEY idx_unique_t_user(`USER_CODE`, `BANK_NO`)
);

-- 密码修改历史表
DROP TABLE IF EXISTS T_PASSWORD_HISTORY;
CREATE TABLE T_PASSWORD_HISTORY(
	ID          BIGINT(20)      NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	USER_CODE   VARCHAR(6)      NOT NULL COMMENT '用户编号/登录账号',
	PASS_WORD   VARCHAR(32)     NOT NULL COMMENT '密码(密文)',
	SALT        VARCHAR(16)     NOT NULL COMMENT '盐',
	BANK_NO     VARCHAR(3)      NOT NULL COMMENT '银行号',
	CREATE_DATE DATETIME        NOT NULL COMMENT '创建时间',
	PRIMARY KEY (id)
);