DROP TABLE IF EXISTS T_USER;
CREATE TABLE T_USER(
	ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	USER_NAME VARCHAR(30) DEFAULT NULL COMMENT '用户名',
	PASS_WORD VARCHAR(30) DEFAULT NULL COMMENT '密码(密文)',
	SALT VARCHAR(30) DEFAULT NULL COMMENT '盐',
	BANK_NO VARCHAR(3) DEFAULT NULL COMMENT '银行号',
	ROLES VARCHAR(30) DEFAULT NULL COMMENT '角色',
	PERMS VARCHAR(200) DEFAULT NULL COMMENT '权限(以英文逗号隔开)',
	`STATUS`INT DEFAULT 0 COMMENT '状态[0-正常，1-锁定]',
	PRIMARY KEY (id),
	UNIQUE KEY uni_user(`USER_NAME`)
);