server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: service-one

# 健康检查，端点暴露
management:
  endpoints:
    web:
      exposure:
        include: '*'    # 端点查询 http://localhost:8081/actuator/health或routes或filters等
    health:
      show-details: always

logging:
  level:
    com.bocsoft.obss.zuul: debug
